version: "3.9"

services:
  db:
    container_name: db
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - TZ=Asia/Seoul
      - POSTGRES_DB=openadr
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    build:
      context: BackEnd
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./BackEnd:/project
    environment:
      TZ: Asia/Seoul
    depends_on:
      - db

  model:
    container_name: model
    build:
      context: Model
      dockerfile: Dockerfile
    volumes:
      - ./Model:/project
#    tty : true
    environment:
      - TZ=Asia/Seoul
    # 환경변수 설정 파일
    env_file:
      - model-variables.env