# Generated by Django 3.2.4 on 2021-07-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipments_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteId', models.CharField(max_length=50)),
                ('perfId', models.SmallIntegerField()),
                ('eqpCode', models.CharField(max_length=200)),
                ('eqpName', models.CharField(max_length=200)),
                ('eqpType', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='power_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteId', models.CharField(max_length=50)),
                ('perfId', models.CharField(max_length=50)),
                ('pnName', models.CharField(max_length=50)),
                ('eqpName', models.CharField(max_length=50)),
                ('ymdms', models.CharField(max_length=50)),
                ('volTage', models.CharField(max_length=50)),
                ('amPere', models.CharField(max_length=50)),
                ('arPower', models.CharField(max_length=50)),
                ('atvPower', models.CharField(max_length=50)),
                ('ratPower', models.CharField(max_length=50)),
                ('pwFactor', models.CharField(max_length=50)),
                ('accruePower', models.CharField(max_length=50)),
                ('voltagerS', models.CharField(max_length=50)),
                ('voltagesT', models.CharField(max_length=50)),
                ('voltagetR', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
