# Generated by Django 3.2.4 on 2021-08-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_collect', '0002_auto_20210727_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power_info',
            name='perf_id',
            field=models.SmallIntegerField(),
        ),
    ]
